# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
        composer_args:
          - ''
          - '--prefer-stable'
          - '--prefer-stable --prefer-lowest'
    name: PHP ${{ matrix.php }} ${{ matrix.composer_args }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Build
        env:
          COMPOSER_ARGS: ${{ matrix.composer_args }}
        run: composer update --no-interaction --no-progress --prefer-dist $COMPOSER_ARGS
      - name: Tests
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
      
      - name: "Send code coverage report to Codecov.io"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        run: "bash <(curl -s https://codecov.io/bash) || true"  
       
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_SERVICE_NAME: github
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "vendor/bin/php-coveralls --config tests/coveralls.yml -v"
        
